### ISSUE TITLE
Make a Docker Container

### ISSUE THREAD

**Issue by tarunnsingh** [tarunnsingh/morph-client#3]
### Problem
Currently this repo combined with the [server](https://github.com/tarunnsingh/morph-server) repo, together are required to build the project. The Flask server and the React frontend need to be built under a single image, anyhow? Has this been NodeJs, it would be super easy to do. Moreover if you suggest to host both repos separately, then I am receiving problems with DLIB while trying to deploy this Flask Server on Heroku.

Is it possible to combine both using **Docker**.

### If yes, any help would be appreciated.

**Comment by cacevedo-dev** [comment]
Hey @tarunnsingh being these two different repos building a single image is not possible since it should be hold in one of these, and the other files would not be _visible_ for the image. Also, it's better to have them in separate images (even if they were in the same repo) in order to keep the images lightweigth with only the required files and dependencies in them.

**Comment by tarunnsingh** [comment]
Hey! @Charles06x , I understood your point. So if we create separate images for each repo, then it must be easy to run two images concurrently, right? 
PS: I am new to containers, so these questions may sound trash.

**Comment by cacevedo-dev** [comment]
Yes, we'd just need to ensure the communication between the two containers over the network and they'll work. Think it as if you deploy them into two different machines, and you use the ip or the DNS of each one to perform the communication. With docker containers we'd do something like that. 

BTW, I tried to add a new branch for creating the docker images and I was not able to do so. 🤔 Are you ok with me helping with that?

**Comment by tarunnsingh** [comment]
Yes sure! I am open to any kind of help on this. Do I need to provide some more information on the environment, for you to get started?
If you are wiling to work on this, shall I assign you?

**Comment by cacevedo-dev** [comment]
Sure, I can help you with it. I'll try checking the Readme and see if everything is ok for me to get started. 

And yes, you can assing me 🤙🏼

**Comment by tarunnsingh** [comment]
Hey @Charles06x were you able to run the Server Repo locally?

**Comment by cacevedo-dev** [comment]
Actually, I had an issue with the OpenCV module. Which Python Version is required for the server? @tarunnsingh

**Comment by tarunnsingh** [comment]
I used `python 3.6.0` and `pip 9.0.1`.

**Comment by cacevedo-dev** [comment]
Dude, I've try to do some commits in both repo and I have no write access. 🤔

**Comment by tarunnsingh** [comment]
You need to FORK the repositories to do that. 😄

**Comment by jabhishek87** [comment]
do you still need help ?

**Comment by tarunnsingh** [comment]
I still am not able to run it using the docker-compose file, the build runs just fine. Both of them are built successfully but on going to port 3000 of localhost the app dosen't start, even though I have provided explicitly to map 3000 to 3000. 😕

**Comment by cacevedo-dev** [comment]
Give me a moment and I'll take a look on it @jabhishek87 👍

**Comment by cacevedo-dev** [comment]
Hey @tarunnsingh sorry for my late response. I created this PR for fixing the issue. There was a missing attribute in the compose file for the client app build, and the container exited after the startup. I added it, and I was able to navigate to localhost:3000 and see the app running. Could you test the changes and let me know if everything is ok.

Will be aware if you have feedbacks. This is the [PR](https://github.com/tarunnsingh/morph-client/pull/8).

**Comment by tarunnsingh** [comment]
> Hey @tarunnsingh sorry for my late response. I created this PR for fixing the issue. There was a missing attribute in the compose file for the client app build, and the container exited after the startup. I added it, and I was able to navigate to localhost:3000 and see the app running. Could you test the changes and let me know if everything is ok.
> 
> Will be aware if you have feedbacks. This is the [PR](https://github.com/tarunnsingh/morph-client/pull/8).

Works like a charm!! thanks!

**Comment by cacevedo-dev** [comment]
Perfect! 🙌🏼🎉

> Works like a charm!! thanks!
