### ISSUE TITLE
Display a Nice Spinner/Loading Animation

### ISSUE THREAD

**Issue by tarunnsingh** [tarunnsingh/morph-client#4]
### - **When tapped on the Download Button** , the following text and Spinner shows up.
![Screenshot (16)](https://user-images.githubusercontent.com/31896659/94770857-5260f200-03d3-11eb-874a-a13e6865dc92.png)

### Add some interesting animation/spinner/changing-text etc. in it's place.

**Comment by asi309** [comment]
I can work on this issue

**Comment by tarunnsingh** [comment]
Hey @asi309 , please make sure that you are able to run the project locally.
Once done, I will assign you.

**Comment by asi309** [comment]
While setting up your server repo, pip install cmake is not working. I can run the frontend locally and there is no issue

> Hey @asi309 , please make sure that you are able to run the project locally.
> Once done, I will assign you.

**Comment by tarunnsingh** [comment]
> While setting up your server repo, pip install cmake is not working. I can run the frontend locally and there is no issue
> 
> > Hey @asi309 , please make sure that you are able to run the project locally.
> > Once done, I will assign you.

What error is it throwing?

**Comment by asi309** [comment]
> > While setting up your server repo, pip install cmake is not working. I can run the frontend locally and there is no issue
> > > Hey @asi309 , please make sure that you are able to run the project locally.
> > > Once done, I will assign you.
> 
> What error is it throwing?

No module found for pip.req while installing cmake

**Comment by tarunnsingh** [comment]
I am using `pip 9.0.1`, and from [here](https://gitlab.kitware.com/cmake/cmake/-/issues/17950) it looks like in newer versions of pip (> 10.x.x) will throw this error.
Try installing cmake from https://pypi.org/project/cmake/ or pull down your pip to the version mentioned above.

If you come up with a solution, would encourage you to give a PR on the same.
